language: cpp

compiler:
- clang
os:
- osx
osx_image: xcode12

script:
- mkdir build
- cd build && cmake ..
- cmake --build . --target jetpack-test --config Release
- ./bundler/jetpack-test

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
