language: cpp

compiler:
- clang
os:
- osx
osx_image: xcode12

script:
- mkdir cmake-build-release
- cd cmake-build-release && cmake ..
- cmake --build . --target jetpack-test --config Release
- cmake --build . --target jetpackd --config Release
- ./jetpack/jetpack-test

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
